### ISSUE TITLE
Improving ui

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/Calculator#2]

**Comment by abantika27** [comment]
@Kritika30032002 can you please assign this issue to me?

**Comment by Ankita0125** [comment]
can you assign this issue to me @Kritika30032002

**Comment by priyanka1551** [comment]
@Kritika30032002 Can u assign this issue to me

**Comment by realsh9dy** [comment]
the ui can further be improved. i can help you do so in minimal amount of time and with advanced skillset. please assign me this issue if its still live or relevant.

**Comment by Pritam1136** [comment]
I am new to open source but I think  that I can improve the UI of the application. Can you please assign this issue to me?
